# Generated by Django 3.2.4 on 2021-08-03 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='score',
        ),
    ]
